"""Refactor table schema

Revision ID: f67eb51ece63
Revises: 7bdac297adbd
Create Date: 2025-03-27 12:26:13.371822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f67eb51ece63'
down_revision: Union[str, None] = '7bdac297adbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.Column('filing_type', sa.String(), nullable=True),
    sa.Column('filing_date', sa.DateTime(), nullable=True),
    sa.Column('filing_url', sa.String(), nullable=True),
    sa.Column('filing_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filings_id'), 'filings', ['id'], unique=False)
    op.drop_index('ix_edgar_filings_id', table_name='edgar_filings')
    op.drop_table('edgar_filings')
    op.drop_index('ix_tickers_symbol', table_name='tickers')
    op.drop_column('tickers', 'sector')
    op.drop_column('tickers', 'industry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickers', sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tickers', sa.Column('sector', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_tickers_symbol', 'tickers', ['symbol'], unique=True)
    op.create_table('edgar_filings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filing_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('filing_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('filing_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('filing_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('filing_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name='edgar_filings_ticker_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='edgar_filings_pkey')
    )
    op.create_index('ix_edgar_filings_id', 'edgar_filings', ['id'], unique=False)
    op.drop_index(op.f('ix_filings_id'), table_name='filings')
    op.drop_table('filings')
    # ### end Alembic commands ###
